'use strict';

const {
  COLORS, formatDate, formatMetal, statusColor, priorityColor,
} = require('../pdfPrimitives');

module.exports = {
  id: 'enquiries-list',
  title: 'Enquiries List Report',
  layout: 'table',
  baseFilters: {},
  rowHeight: 46,
  headerRowHeight: 24,
  columns: [
    { header: '#', width: 22, align: 'center',
      render: (_row, i) => i + 1,
      textOpts: { align: 'center', color: COLORS.textMuted } },
    { header: 'Name', width: 178,
      render: (row) => row.Name || '',
      textOpts: { bold: true, fontSize: 9 } },
    { header: 'Category', width: 56,
      render: (row) => row.Category || 'N/A',
      textOpts: { color: COLORS.textMuted } },
    { header: 'Status', width: 60, kind: 'badge',
      render: (row) => row.CurrentStatus || 'pending',
      color: (row) => statusColor(row.CurrentStatus) },
    { header: 'Client', width: 64,
      render: (row, _i, ctx) => ctx.clientsMap[row.ClientId?.toString()] || 'N/A' },
    { header: 'Image', width: 46, align: 'center', kind: 'image' },
    { header: 'Assigned To', width: 64,
      render: (row, _i, ctx) => ctx.usersMap[row.AssignedTo?.toString()] || 'N/A' },
    { header: 'Assigned Date', width: 54,
      render: (row) => formatDate(row.AssignedDate),
      textOpts: { color: COLORS.textMuted } },
    { header: 'Created Date', width: 54,
      render: (row) => formatDate(row.CreatedDate),
      textOpts: { color: COLORS.textMuted } },
    { header: 'Priority', width: 58, kind: 'badge',
      render: (row) => row.Priority || 'medium',
      color: (row) => priorityColor(row.Priority) },
    { header: 'Metal', width: 76,
      render: (row) => formatMetal(row.Metal) },
    { header: 'Stone Type', width: 56,
      render: (row) => row.StoneType || 'N/A',
      textOpts: { color: COLORS.textMuted } },
    { header: 'Shipping Date', width: 54,
      render: (row) => row.ShippingDate ? formatDate(row.ShippingDate) : 'Not set',
      textOpts: { color: COLORS.text } },
  ],
};
